# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 6fca98ce4c4c364c22dfccbd66eaf58daddbfc5be5f44fcd22fd05154466a9802340d87ccff0f6f3949668137acf04482fec18f362ee06b85b506a67d583a974

test:
  secret_key_base: 13b63c58e5f86b097941fc02c98f2747605da0124d25a17c2961c565feaae7d618a7b96fe6e0a159d0a8f4af75bd3bdf5ffbeb7a97b50d9c0c5df63ac3258fff

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
